apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata: # kpt-merge: default/app-deploy
  name: profile-operator-post-deploy
  namespace: profile-operator
  annotations:
    internal.kpt.dev/upstream-identifier: 'kustomize.toolkit.fluxcd.io|Kustomization|default|profile-operator-post-deploy'
spec:
  dependsOn:
  - name: profile-operator-deploy
  sourceRef:
    kind: GitRepository
    name: nc-app
  path: "./profile-operator/post-deploy/"
  interval: 60m
  timeout: 5m
  prune: true
  wait: true