apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata: # kpt-merge: default/frofile-operator-ms
  name: profile-operator
  namespace: 
  annotations:
    internal.kpt.dev/upstream-identifier: 'helm.toolkit.fluxcd.io|HelmRelease|default|profile-operator'
spec:
  chart:
    spec:
      chart: ./profile-operator/helmcharts/ncm-app-2.3.1.tgz  # kpt-set: ./${targetNamespace}/
      version: '1.0.0'
      sourceRef:
        kind: GitRepository
        name: nc-app # kpt-set: ${gitreponame}
        namespace: default
      reconcileStrategy: Revision
      interval: 1m
  targetNamespace: profile-operator
  valuesFrom:
  - kind: ConfigMap
    name: profile-operator-values
    valuesKey: values.yaml