kind: ConfigMap
metadata: # kpt-merge: example/profile-operator-values
  name: profile-operator-values
  namespace: profile-operator
  annotations:
    internal.kpt.dev/upstream-identifier: '|ConfigMap|example|profile-operator-values'
apiVersion: v1
data:
  values.yaml: |
    replicaCount: 1  # kpt-set: ${replicas}
    image:
      tag: latest
    autonomous:
      enabled: true
    webhook:
      validate: false
    controller: true
    helm3Only: true
    checkLabelling: false